name: citas_medicas_app
description: App de ejemplo para gestionar citas mÃ©dicas con Firebase
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Ãconos de iOS
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.20.0
  cloud_firestore: ^4.7.0
  firebase_auth: ^4.8.0

  # Utilidades
  intl: ^0.18.0

  # Notificaciones locales
  flutter_local_notifications: ^17.0.0

  # Calendario
  table_calendar: ^3.0.9

  # Provider (ðŸ”¥ agregado)
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
